services:
  # scrapers:
  #   build: ./scrapers
  #   volumes:
  #     - ./scrapers:/app
  #     - ./scrapers/data:/app/data
  #   env_file:
  #     - ./scrapers/.env
  #   networks:
  #     - app-network
  #   depends_on:
  #     - database

  backend:
    build: ./backend
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - C:/Users/Hadi/Downloads/ca.pem:/app/ca.pem
    networks:
      - app-network
    restart: on-failure
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000" 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3001
      - REACT_APP_API_URL=http://localhost:8001
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app:cached
      - frontend_node_modules:/usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: markaba-network

volumes:
  frontend_node_modules:
