location: uaenorth
resourceGroup: markaba-app-rg
properties:
  configuration:
    ingress:
      external: true
      targetPort: 80
      transport: auto
    registries:
    - server: markabaregistry2025.azurecr.io
      identity: system
  template:
    containers:
    - image: markabaregistry2025.azurecr.io/markaba-frontend:v1
      name: markaba-frontend-app
      resources:
        cpu: 0.5
        memory: 1Gi
